// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  isRated: boolean = false;
  choice: number = 0;
}

<form class="form" ngSubmit="handleSubmit">
  <app-rating-component
    *ngIf="!isRated"
    [error]="false"
    [choice]="0"
  ></app-rating-component>
  <app-result-component *ngIf="isRated" [choice]="2"></app-result-component>
</form>

// src/app/App.tsx
import { useEffect, useState } from "react";
import { Rating } from "../components/Rating";
import { Result } from "../components/Result";

function App() {
  const [isRated, setIsRated] = useState<boolean>(false);
  const [value, setValue] = useState<number>(0);
  const [error, setError] = useState<boolean>(false);

  const handleSubmit = () => {
    if (!value) {
      setError(true);
    } else {
      setIsRated(true);
    }
  };

  useEffect(() => {
    if (value) setError(false);
  }, [value]);

  return (
    <div className="form">
      {!isRated ? (
        <Rating
          value={value}
          setValue={setValue}
          error={error}
          handleSubmit={handleSubmit}
        />
      ) : (
        <Result value={value} />
      )}
    </div>
  );
}

export default App;
