// src/lib/Rating.svelte
<script lang="ts">
  import IconStar from "./IconStar.svelte";
  import BlockText from "./BlockText.svelte";
  import CardContainer from "./CardContainer.svelte";

  export let choice: number;
  export let error: boolean;
  export let updateValue;

  const VALUES = [1, 2, 3, 4, 5];
</script>

<CardContainer>
  <IconStar />
  <BlockText
    title="How did we do?"
    text="Please let us know how we did with your support request. All feedback is
      appreciated to help us improve our offering!"
  />

  <ol>
    {#each VALUES as value}
      <li>
        <button
          type="button"
          aria-label="Choose a rate"
          on:click={updateValue(value)}
          class:selected="{value === choice}"
        >
        { value }
        </button>
      </li>
    {/each}
  </ol>

  {#if error}<p class="error">You have to make a choice!</p>{/if}

  <button type="submit" aria-label="Send your rate">Submit</button>
</CardContainer>

// src/app/rating-component/rating-component.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-rating-component',
  templateUrl: './rating-component.component.html',
  styleUrls: ['./rating-component.component.css'],
})
export class RatingComponentComponent implements OnInit {
  @Input() error: boolean = false;
  @Input() choice: number = 0;

  VALUES: number[] = [1, 2, 3, 4, 5];

  constructor() {}

  ngOnInit(): void {}

  updateValue(value: number) {
    console.log(value);
    this.choice = value;
  }
}

<app-card-container>
  <app-icon-star></app-icon-star>
  <app-block-text
    title="How did we do?"
    text="Please let us know how we did with your support request. All feedback is
        appreciated to help us improve our offering!"
  ></app-block-text>
  {{ choice }}
  <ol>
    <li *ngFor="let value of VALUES">
      <button
        type="button"
        aria-label="Choose a rate"
        (click)="updateValue(value)"
        [class.selected]="value === choice"
      >
        {{ value }}
      </button>
    </li>
  </ol>
  <p class="error" *ngIf="error">You have to make a choice!</p>

  <button type="submit" aria-label="Send your rate">Submit</button>
</app-card-container>
