// src/app/result-component/result-component.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-result-component',
  templateUrl: './result-component.component.html',
  styleUrls: ['./result-component.component.css'],
})
export class ResultComponentComponent implements OnInit {
  @Input() choice: number = 0;

  constructor() {}

  ngOnInit(): void {}
}

<app-card-container [className]="'align-items-center'">
  <app-illustration-component></app-illustration-component>

  <span class="badge">
    You selected <span>{{ choice }}</span> out of 5
  </span>

  <app-block-text
    title="Thank you"
    text="We appreciate you taking the time to give a rating. If you ever need
        more support, don’t hesitate to get in touch!"
  ></app-block-text>
</app-card-container>

// src/components/Result.tsx
import { BlockText } from "./BlockText";
import { Illustration } from "./Illustration";

interface IResult {
  value: number;
}

export const Result = ({ value = 0 }: IResult) => {
  return (
    <fieldset className="align-items-center">
      <Illustration />

      <span className="badge">
        You selected <span>{value}</span> out of 5
      </span>

      <BlockText
        title="Thank you"
        text="We appreciate you taking the time to give a rating. If you ever need
        more support, don’t hesitate to get in touch!"
      />
    </fieldset>
  );
};
