// src/App.vue
<script setup lang="ts">
// vue imports
import { ref, watch } from "vue";
// components imports
import Rating from "@/components/Rating.vue";
import Result from "@/components/Result.vue";
// declarations
let isRated: boolean = ref(false);
let choice: number = ref(0);
let error: boolean = ref(false);

const handleSubmit = e => {
  e.preventDefault();
  if (!choice.value) {
    error.value = true;
  } else {
    isRated.value = true;
  }
};

const updateValue = selectedValue => (choice.value = selectedValue);

watch(choice, () => {
  if (choice.value) error.value = false;
});
</script>

<template>
  <form className="form" @submit="handleSubmit">
    <Rating
      v-if="!isRated"
      :choice="choice"
      :error="error"
      :updateValue="updateValue"
    />
    <Result v-else :choice="choice" />
  </form>
</template>

<style>
@import "./assets/index.css";
</style>

// src/App.svelte
<script setup lang="ts">
  // components imports
  import Rating from "./lib/Rating.svelte";
  import Result from "./lib/Result.svelte";
  // declarations
  let isRated: boolean = false;
  let choice: number = 0;
  let error: boolean = false;

  $: if (choice) error = false;
  
  const handleSubmit = e => {
    e.preventDefault();
    if (!choice) {
      error = true;
    } else {
      isRated = true;
    }
  };
  
  const updateValue = selectedValue => (choice = selectedValue);
  
</script>
  
<form class="form" on:submit={handleSubmit}>
  {#if !isRated }
  <Rating choice={choice} error={error} updateValue={updateValue} />
  {:else}
  <Result choice={choice} />
  {/if}
</form>
  
<style>
@import "./assets/index.css";
</style>
