// src/app/App.tsx
import { useEffect, useState } from "react";
import { Rating } from "../components/Rating";
import { Result } from "../components/Result";

function App() {
  const [isRated, setIsRated] = useState<boolean>(false);
  const [value, setValue] = useState<number>(0);
  const [error, setError] = useState<boolean>(false);

  const handleSubmit = () => {
    if (!value) {
      setError(true);
    } else {
      setIsRated(true);
    }
  };

  useEffect(() => {
    if (value) setError(false);
  }, [value]);

  return (
    <div className="form">
      {!isRated ? (
        <Rating
          value={value}
          setValue={setValue}
          error={error}
          handleSubmit={handleSubmit}
        />
      ) : (
        <Result value={value} />
      )}
    </div>
  );
}

export default App;

// src/App.vue
<script setup lang="ts">
// vue imports
import { ref, watch } from "vue";
// components imports
import Rating from "@/components/Rating.vue";
import Result from "@/components/Result.vue";
// declarations
let isRated: boolean = ref(false);
let choice: number = ref(0);
let error: boolean = ref(false);

const handleSubmit = e => {
  e.preventDefault();
  if (!choice.value) {
    error.value = true;
  } else {
    isRated.value = true;
  }
};

const updateValue = selectedValue => (choice.value = selectedValue);

watch(choice, () => {
  if (choice.value) error.value = false;
});
</script>

<template>
  <form className="form" @submit="handleSubmit">
    <Rating
      v-if="!isRated"
      :choice="choice"
      :error="error"
      :updateValue="updateValue"
    />
    <Result v-else :choice="choice" />
  </form>
</template>

<style>
@import "./assets/index.css";
</style>
